config/routes.rb
Coffeenapkins::Application.routes.draw do

  devise_for :users
  resources :napkins do
  	resources :comments
  end

  root 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :napkin
end

app/models/napkin.rb
class Napkin < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @napkin = Napkin.find(params[:napkin_id])
    @comment = @napkin.comments.create(comment_params)
    redirect_to napkin_path(@napkin)
  end

  def destroy
    @napkin = Napkin.find(params[:napkin_id])
    @comment = @napkin.comments.find(params[:id])
    @comment.destroy
    redirect_to napkin_path(@napkin)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/napkins_controller.rb
class NapkinsController < ApplicationController

  def new
  	@napkin = Napkin.new
  end

  def create
  	@napkin = Napkin.new(napkin_params)

  	if @napkin.save
  	  redirect_to @napkin
  	else
  	  render 'new'
  	end
  end

  def edit
  	@napkin = Napkin.find(params[:id])
  end

  def update
  	@napkin = Napkin.find(params[:id])

  	if @napkin.update(napkin_params)
  	  redirect_to @napkin
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	@napkin = Napkin.find(params[:id])
  	@napkin.destroy

  	redirect_to napkins_path
  end

  def show
    @napkin = Napkin.find(params[:id])
  end

  def index
  	@napkins = Napkin.all
  end

  private
    def napkin_params
      params.require(:napkin).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def full_title(page_title)
  base_title = "Coffee Napkins"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/napkins_helper.rb
module NapkinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

<p>
	<%= link_to 'Remove Comment', [comment.napkin, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@napkin, @napkin.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "Home",    '#' %></li>
<li><%= link_to "Help",    '#' %></li>
<li><%= link_to "Sign in", '#' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>

		<nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
		    </div>
		    <div class="collapse navbar-collapse">
		      <ul class="nav navbar-nav">
		        <%= render 'layouts/navigation_links' %>
		      </ul>
		    </div>
		  </div>
		</nav>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<div class="container">
		  <%= yield %>
		</div>

	</body>
</html>

app/views/napkins/_form.html.erb
 <%= form_for @napkin do |f| %>
  <% if @napkin.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@napkin.errors.count, "error") %> prohibited
      this napkin idea from being saved:</h2>
    <ul>
    <% @napkin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/napkins/edit.html.erb
<h1>Edit Napkin</h1>

<%= render 'form' %>
 
<%= link_to 'Back', napkins_path %>

app/views/napkins/index.html.erb
<h1>All napkins</h1>

<%= link_to 'Jot down an idea', new_napkin_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @napkins.each do |napkin| %>
    <tr>
      <td><%= napkin.title %></td>
      <td><%= napkin.text %></td>
      <td><%= link_to 'View', napkin_path(napkin) %></td>
      <td><%= link_to 'Edit', edit_napkin_path(napkin) %></td>
      <td><%= link_to 'Delete', napkin_path(napkin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Jot down an idea', new_napkin_path %>

app/views/napkins/new.html.erb
<h1>New Napkin</h1>

<%= render 'form' %>

<%= link_to 'Back', napkins_path %>

app/views/napkins/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @napkin.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @napkin.text %>
</p>

<h2>Comments</h2>
<%= render @napkin.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit this idea', edit_napkin_path(@napkin) %><br>
<%= link_to 'Back', napkins_path %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<%= link_to 'Napkins', controller: 'napkins' %>